version: '3.8'

services:
    
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/client

  server:
    build: ./server
    ports:
      - 8000:8000
    volumes:
      - ./server:/server